version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234!
      MYSQL_DATABASE: practice
    ports:
      - '3306:3306'
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'
  api_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api_server_container
    depends_on:
      - db
    volumes:
      - ./server/src:/app/src
    ports:
      - '8001:8001'
      - '5555:5555'
    environment:
      - SERVER_PORT=8001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_container
    depends_on:
      - api_server
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    environment:
      - REACT_APP_API_URL=http://localhost:8001
      - REACT_APP_PUBLISHABLE_STRIPE_KEY=pk_test_51PdmCGRv8HKFmcvf8XjWAZ1LMzF7dKL01Gq6I39FGTT5tb73kgKIiOxC1vqfYMKT74XxgverDOsLYYhwcApkioEP00PNeSRKCA
